fix file mandatory
prest/config pull request #16
Opened 2017-12-13 20:37 UTC by felipeweb

related issue https://github.com/prest/prest/issues/257

2017-12-13 22:36 UTC, crgimenes approved these changes

2017-12-13 23:22 UTC, avelino requested changes

2017-12-13 23:22 UTC, avelino commented on config.go
> +var defaultFile = "./prest.toml"
group `vars`

2017-12-14 12:04 UTC, sebawebber requested changes

2017-12-14 12:04 UTC, sebastianwebber commented on config_test.go
>  func TestGetDefaultPrestConf(t *testing.T) {
please convert this to a test table.

2017-12-14 13:13 UTC, lerrua approved these changes

2017-12-14 13:42 UTC, crgimenes approved these changes
LGTM

2017-12-14 14:04 UTC, merged