database connection url support
prest/config pull request #23
Opened 2018-07-22 10:49 UTC by avelino

ref #315

2018-07-22 14:53 UTC, felipeweb requested changes
Just a few comments

2018-07-22 14:53 UTC, felipeweb commented on config.go
> +			return err
The function uses  named returning please do not mix the ways to returning

2018-07-22 14:53 UTC, felipeweb commented on config.go
> +			cfg.SSLMode = u.Query()["sslmode"][0]
can be used u.Query().Get(“sslmode”)

2018-07-23 00:13 UTC, crgimenes approved these changes
LGTM

2018-07-23 01:31 UTC, felipeweb approved these changes

2018-07-23 01:33 UTC, merged