restructuring for use of more than one database adapter / config
prest/config pull request #7
Opened 2017-09-13 00:01 UTC by joelmdesouza

-created Adapter, type interface adapter

2017-09-15 13:33 UTC, felipeweb requested changes

2017-09-15 13:33 UTC, felipeweb commented on config.go
> +var Adapter adapters.Adapter
adapter don't need to be global can be a field of Prest struct

2017-10-09 00:57 UTC, avelino approved these changes
LGTM

2017-10-09 12:43 UTC, crgimenes approved these changes
LGTM

2017-10-24 21:08 UTC, lerrua commented
@joelmdesouza do you need some help to solve file conflicts? This PR is blocking https://github.com/prest/prest/pull/218 and https://github.com/prest/adapters/pull/15.

2017-10-26 21:45 UTC, joelmdesouza commented
@lerrua done

2017-10-26 21:55 UTC, joelmdesouza commented
@lerrua 
When it was committed there was no conflict, the conflict occurred after merge another PR.
I only heard of the conflict after you warned me.
Sorry for the delay.
Thank you for the warning.

2017-10-28 14:41 UTC, merged